### ISSUE TITLE
[PROBLEM] There is no signal from the speaker of the LTN station

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Quezler/glutenfree#3]
### Modpack Version

Glutenfree LTN announcer 1.0.6

### Describe your issue.

I installed the mod, went into the game where LTN stations were already standing, waited for a train to go to one to see the signals, but there were none. I thought that the problem was that the station was already standing, but after removing and reinstalling the station, the situation has not changed

![image](https://user-images.githubusercontent.com/46845681/191737709-5214ef9f-2f96-480e-a34a-ea70540e8cda.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Quezler** [comment]
yes, there are some issues due to how LTN's own dispatcher event works, causing the signal to only update for stations that had multiple incoming trains (a new train being dispatched would update the speaker's signal for all trains that were en-route to it already), i was already planning a fix a few days ago, and it'll likely arrive within 1-2 days. ^-^

**Comment by Eldrinn-Elantey** [comment]
> yes, there are some issues due to how LTN's own dispatcher event works, causing the signal to only update for stations that had multiple incoming trains (a new train being dispatched would update the speaker's signal for all trains that were en-route to it already), i was already planning a fix a few days ago, and it'll likely arrive within 1-2 days. ^-^

I am glad to hear that work on such a useful mod is underway. By the way, I forgot to add a screenshot to the ticket, I'll go fix it

**Comment by Quezler** [comment]
Always glad to hear when other people love my work, as for the fix: i have just put out 1.0.7 🎉

Under the hood it works [rather differently](https://github.com/Quezler/glutenfree/compare/f80a4092628345c39ff6422808af866a2a6a9ab6...main), but as far as players are concerned the mod has improved.

A slight drawback however of the update is that there is currently no support for trains that pickup/deliver several items and/or visit more than two stations, it might "sorta" work, but it is untested since i only roll with full trains on my testing map.

(for those that require said support & read this, if you send me a blank test world with just a simple ltn setup that showcases my mod improperly working i am willing to implement support for it, but i don't want to create a test world myself)

</>

So anyways @Eldrinn-Elantey, let me know if your issue listed at the top is now fixed 🍿

**Comment by Quezler** [comment]
scratch that, try version 1.0.10, there were some issues with the load order when the mod was a folder vs a zip. 😅

**Comment by Eldrinn-Elantey** [comment]
The signal appeared.

![image](https://user-images.githubusercontent.com/46845681/191816361-65a2b7a9-c9d2-4111-acb0-229b8eacad3b.png)

In the screenshot, there is a station with two trains, one is already loading the second in line. The copper signal is 502, but this is the signal from the second train. The one that is already standing at the station is waiting for 1600 copper. Is it possible to make sure that the signal does not disappear after the train has arrived at the station and, for example, when it has left it?

**Comment by Quezler** [comment]
i designed the mod with the idea in mind that the signal shows the trains that haven't arrived yet, and as for getting the signal of the currently stopped train you should be able to just use the combinator (to which you've already attached a green wire) 🤔

**Comment by Quezler** [comment]
in my current base you can see the designed usecase:

![Screenshot 2022-09-22 at 20 03 41](https://user-images.githubusercontent.com/3179271/191819420-e6dfcd33-3816-4d0d-8f44-9efa2a0ed9c1.png)

this is your typical "request these items from the logistic network when a train is at the station to request items", and the purpose of the announcer is to let you know which deliveries or pickups are "about to" arrive in the future, so you can use it's signal to prepare the items the train expects prior to its arrival, once it has arrived the "normal" ltn circutry takes over.

**Comment by Eldrinn-Elantey** [comment]
> which part?

According to your idea, is it normal that the signal from the speaker disappears when the train arrives at the station?

**Comment by Quezler** [comment]
yes, because once the train has arrived the ltn combinator (greenish yellow thing) outputs the signal of what the train wants or delivers.
